spring:
  data:
    mysql:
      host: mysql
      port: 3306
  application:
    name: master-spring-boot-final-project
logging:
  level:
    root: DEBUG
management:
  endpoints:
    enable-by-default: false
    web:
      exposure:
        include: health, info, beans, threaddump, mappings, prometheus
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      show-components: always
      enabled: true
    beans:
      enabled: true
    threaddump:
      enabled: true
    mappings:
      enabled: true
    prometheus:
      enabled: true