scrape_configs:
  - job_name: 'master-spring-boot-base-project-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'master-spring-boot-base-project'